/**
 * Fallback dex → primary type table.
 *
 * Used by `resolveCardType` when a Korean card name does not have a direct
 * entry in `CARD_NAME_TO_TYPE`: we look up the National Dex number via
 * `CARD_NAME_TO_DEX`, then read the primary (slot 1) type from this table.
 *
 * Covers National Dex #1 (Bulbasaur) through #1025 (Pecharunt).
 * For dual-type Pokémon, only the primary slot type is recorded.
 * For Pokémon with regional / form variants, the original (Kanto / base)
 * form's primary type is used.
 */

import type { WildType } from "./types";

export const DEX_TO_TYPE: Record<number, WildType> = {
  // ── Gen 1 (1–151) ────────────────────────────────────────────────
  1: "풀",        // 이상해씨 Bulbasaur
  2: "풀",        // 이상해풀 Ivysaur
  3: "풀",        // 이상해꽃 Venusaur
  4: "불꽃",      // 파이리 Charmander
  5: "불꽃",      // 리자드 Charmeleon
  6: "불꽃",      // 리자몽 Charizard
  7: "물",        // 꼬부기 Squirtle
  8: "물",        // 어니부기 Wartortle
  9: "물",        // 거북왕 Blastoise
  10: "벌레",     // 캐터피 Caterpie
  11: "벌레",     // 단데기 Metapod
  12: "벌레",     // 버터플 Butterfree
  13: "벌레",     // 뿔충이 Weedle
  14: "벌레",     // 딱충이 Kakuna
  15: "벌레",     // 독침붕 Beedrill
  16: "노말",     // 구구 Pidgey
  17: "노말",     // 피죤 Pidgeotto
  18: "노말",     // 피죤투 Pidgeot
  19: "노말",     // 꼬렛 Rattata
  20: "노말",     // 레트라 Raticate
  21: "노말",     // 깨비참 Spearow
  22: "노말",     // 깨비드릴조 Fearow
  23: "독",       // 아보 Ekans
  24: "독",       // 아보크 Arbok
  25: "전기",     // 피카츄 Pikachu
  26: "전기",     // 라이츄 Raichu
  27: "땅",       // 모래두지 Sandshrew
  28: "땅",       // 고지 Sandslash
  29: "독",       // 니드런♀ Nidoran♀
  30: "독",       // 니드리나 Nidorina
  31: "독",       // 니드퀸 Nidoqueen
  32: "독",       // 니드런♂ Nidoran♂
  33: "독",       // 니드리노 Nidorino
  34: "독",       // 니드킹 Nidoking
  35: "페어리",   // 삐삐 Clefairy
  36: "페어리",   // 픽시 Clefable
  37: "불꽃",     // 식스테일 Vulpix
  38: "불꽃",     // 나인테일 Ninetales
  39: "노말",     // 푸린 Jigglypuff
  40: "노말",     // 푸크린 Wigglytuff
  41: "독",       // 주뱃 Zubat
  42: "독",       // 골뱃 Golbat
  43: "풀",       // 뚜벅쵸 Oddish
  44: "풀",       // 냄새꼬 Gloom
  45: "풀",       // 라플레시아 Vileplume
  46: "벌레",     // 파라스 Paras
  47: "벌레",     // 파라섹트 Parasect
  48: "벌레",     // 콘팡 Venonat
  49: "벌레",     // 도나리 Venomoth
  50: "땅",       // 디그다 Diglett
  51: "땅",       // 닥트리오 Dugtrio
  52: "노말",     // 나옹 Meowth
  53: "노말",     // 페르시온 Persian
  54: "물",       // 고라파덕 Psyduck
  55: "물",       // 골덕 Golduck
  56: "격투",     // 망키 Mankey
  57: "격투",     // 성원숭 Primeape
  58: "불꽃",     // 가디 Growlithe
  59: "불꽃",     // 윈디 Arcanine
  60: "물",       // 발챙이 Poliwag
  61: "물",       // 슈륙챙이 Poliwhirl
  62: "물",       // 강챙이 Poliwrath
  63: "에스퍼",   // 캐이시 Abra
  64: "에스퍼",   // 윤겔라 Kadabra
  65: "에스퍼",   // 후딘 Alakazam
  66: "격투",     // 알통몬 Machop
  67: "격투",     // 근육몬 Machoke
  68: "격투",     // 괴력몬 Machamp
  69: "풀",       // 모다피 Bellsprout
  70: "풀",       // 우츠동 Weepinbell
  71: "풀",       // 우츠보트 Victreebel
  72: "물",       // 왕눈해 Tentacool
  73: "물",       // 독파리 Tentacruel
  74: "바위",     // 꼬마돌 Geodude
  75: "바위",     // 데구리 Graveler
  76: "바위",     // 딱구리 Golem
  77: "불꽃",     // 포니타 Ponyta
  78: "불꽃",     // 날쌩마 Rapidash
  79: "물",       // 야돈 Slowpoke
  80: "물",       // 야도란 Slowbro
  81: "전기",     // 코일 Magnemite
  82: "전기",     // 레어코일 Magneton
  83: "노말",     // 파오리 Farfetch'd
  84: "노말",     // 두두 Doduo
  85: "노말",     // 두트리오 Dodrio
  86: "물",       // 쥬쥬 Seel
  87: "물",       // 쥬레곤 Dewgong
  88: "독",       // 질퍽이 Grimer
  89: "독",       // 질뻐기 Muk
  90: "물",       // 셀러 Shellder
  91: "물",       // 파르셀 Cloyster
  92: "고스트",   // 고오스 Gastly
  93: "고스트",   // 고우스트 Haunter
  94: "고스트",   // 팬텀 Gengar
  95: "바위",     // 롱스톤 Onix
  96: "에스퍼",   // 슬리프 Drowzee
  97: "에스퍼",   // 슬리퍼 Hypno
  98: "물",       // 크랩 Krabby
  99: "물",       // 킹크랩 Kingler
  100: "전기",    // 찌리리공 Voltorb
  101: "전기",    // 붐볼 Electrode
  102: "풀",      // 아라리 Exeggcute
  103: "풀",      // 나시 Exeggutor
  104: "땅",      // 탕구리 Cubone
  105: "땅",      // 텅구리 Marowak
  106: "격투",    // 시라소몬 Hitmonlee
  107: "격투",    // 홍수몬 Hitmonchan
  108: "노말",    // 내룸벨트 Lickitung
  109: "독",      // 또가스 Koffing
  110: "독",      // 또도가스 Weezing
  111: "땅",      // 뿔카노 Rhyhorn
  112: "땅",      // 코뿌리 Rhydon
  113: "노말",    // 럭키 Chansey
  114: "풀",      // 덩쿠리 Tangela
  115: "노말",    // 캥카 Kangaskhan
  116: "물",      // 쏘드라 Horsea
  117: "물",      // 시드라 Seadra
  118: "물",      // 콘치 Goldeen
  119: "물",      // 왕콘치 Seaking
  120: "물",      // 별가사리 Staryu
  121: "물",      // 아쿠스타 Starmie
  122: "에스퍼",  // 마임맨 Mr. Mime
  123: "벌레",    // 스라크 Scyther
  124: "얼음",    // 루주라 Jynx
  125: "전기",    // 에레브 Electabuzz
  126: "불꽃",    // 마그마 Magmar
  127: "벌레",    // 쁘사이저 Pinsir
  128: "노말",    // 켄타로스 Tauros
  129: "물",      // 잉어킹 Magikarp
  130: "물",      // 갸라도스 Gyarados
  131: "물",      // 라프라스 Lapras
  132: "노말",    // 메타몽 Ditto
  133: "노말",    // 이브이 Eevee
  134: "물",      // 샤미드 Vaporeon
  135: "전기",    // 쥬피썬더 Jolteon
  136: "불꽃",    // 부스터 Flareon
  137: "노말",    // 폴리곤 Porygon
  138: "바위",    // 암나이트 Omanyte
  139: "바위",    // 암스타 Omastar
  140: "바위",    // 투구 Kabuto
  141: "바위",    // 투구푸스 Kabutops
  142: "바위",    // 프테라 Aerodactyl
  143: "노말",    // 잠만보 Snorlax
  144: "얼음",    // 프리져 Articuno
  145: "전기",    // 썬더 Zapdos
  146: "불꽃",    // 파이어 Moltres
  147: "드래곤",  // 미뇽 Dratini
  148: "드래곤",  // 신뇽 Dragonair
  149: "드래곤",  // 망나뇽 Dragonite
  150: "에스퍼",  // 뮤츠 Mewtwo
  151: "에스퍼",  // 뮤 Mew

  // ── Gen 2 (152–251) ──────────────────────────────────────────────
  152: "풀",      // 치코리타 Chikorita
  153: "풀",      // 베이리프 Bayleef
  154: "풀",      // 메가니움 Meganium
  155: "불꽃",    // 브케인 Cyndaquil
  156: "불꽃",    // 마그케인 Quilava
  157: "불꽃",    // 블레이범 Typhlosion
  158: "물",      // 리아코 Totodile
  159: "물",      // 엘리게이 Croconaw
  160: "물",      // 장크로다일 Feraligatr
  161: "노말",    // 꼬리선 Sentret
  162: "노말",    // 다꼬리 Furret
  163: "노말",    // 부우부 Hoothoot
  164: "노말",    // 야부엉 Noctowl
  165: "벌레",    // 레디바 Ledyba
  166: "벌레",    // 레디안 Ledian
  167: "벌레",    // 페이검 Spinarak
  168: "벌레",    // 아리아도스 Ariados
  169: "독",      // 크로뱃 Crobat
  170: "물",      // 초라기 Chinchou
  171: "물",      // 랜턴 Lanturn
  172: "전기",    // 피츄 Pichu
  173: "페어리",  // 삐 Cleffa
  174: "페어리",  // 푸푸린 Igglybuff
  175: "페어리",  // 토게피 Togepi
  176: "페어리",  // 토게틱 Togetic
  177: "에스퍼",  // 네이티 Natu
  178: "에스퍼",  // 네이티오 Xatu
  179: "전기",    // 메리프 Mareep
  180: "전기",    // 보송송 Flaaffy
  181: "전기",    // 전룡 Ampharos
  182: "풀",      // 아르코 Bellossom
  183: "물",      // 마릴 Marill
  184: "물",      // 마릴리 Azumarill
  185: "바위",    // 꼬지모 Sudowoodo
  186: "물",      // 왕구리 Politoed
  187: "풀",      // 통통코 Hoppip
  188: "풀",      // 두코 Skiploom
  189: "풀",      // 솜솜코 Jumpluff
  190: "노말",    // 에이팜 Aipom
  191: "풀",      // 해너츠 Sunkern
  192: "풀",      // 해루미 Sunflora
  193: "벌레",    // 왕자리 Yanma
  194: "물",      // 우파 Wooper
  195: "물",      // 누오 Quagsire
  196: "에스퍼",  // 에브이 Espeon
  197: "악",      // 블래키 Umbreon
  198: "악",      // 니로우 Murkrow
  199: "물",      // 야돈킹 Slowking
  200: "고스트",  // 무우마 Misdreavus
  201: "에스퍼",  // 안농 Unown
  202: "에스퍼",  // 마자용 Wobbuffet
  203: "노말",    // 키링키 Girafarig
  204: "벌레",    // 피콘 Pineco
  205: "벌레",    // 쏘콘 Forretress
  206: "노말",    // 노고치 Dunsparce
  207: "땅",      // 글라이거 Gligar
  208: "강철",    // 강철톤 Steelix
  209: "페어리",  // 블루 Snubbull
  210: "페어리",  // 그랑블루 Granbull
  211: "물",      // 침바루 Qwilfish
  212: "벌레",    // 핫삼 Scizor
  213: "벌레",    // 단단지 Shuckle
  214: "벌레",    // 헤라크로스 Heracross
  215: "악",      // 포푸니 Sneasel
  216: "노말",    // 깜지곰 Teddiursa
  217: "노말",    // 링곰 Ursaring
  218: "불꽃",    // 마그마그 Slugma
  219: "불꽃",    // 마그카르고 Magcargo
  220: "얼음",    // 꾸꾸리 Swinub
  221: "얼음",    // 메꾸리 Piloswine
  222: "물",      // 코산호 Corsola
  223: "물",      // 총어 Remoraid
  224: "물",      // 대포무노 Octillery
  225: "얼음",    // 딜리버드 Delibird
  226: "물",      // 만타인 Mantine
  227: "강철",    // 무장조 Skarmory
  228: "악",      // 델빌 Houndour
  229: "악",      // 헬가 Houndoom
  230: "물",      // 킹드라 Kingdra
  231: "땅",      // 코코리 Phanpy
  232: "땅",      // 코리갑 Donphan
  233: "노말",    // 폴리곤2 Porygon2
  234: "노말",    // 노라키 Stantler
  235: "노말",    // 루브도 Smeargle
  236: "격투",    // 배루키 Tyrogue
  237: "격투",    // 카포에라 Hitmontop
  238: "얼음",    // 뽀뽀라 Smoochum
  239: "전기",    // 에레키드 Elekid
  240: "불꽃",    // 마그비 Magby
  241: "노말",    // 밀탱크 Miltank
  242: "노말",    // 해피너스 Blissey
  243: "전기",    // 라이코 Raikou
  244: "불꽃",    // 앤테이 Entei
  245: "물",      // 스이쿤 Suicune
  246: "바위",    // 애버라스 Larvitar
  247: "바위",    // 데기라스 Pupitar
  248: "바위",    // 마기라스 Tyranitar
  249: "에스퍼",  // 루기아 Lugia
  250: "불꽃",    // 칠색조 Ho-Oh
  251: "에스퍼",  // 세레비 Celebi

  // ── Gen 3 (252–386) ──────────────────────────────────────────────
  252: "풀",      // 나무지기 Treecko
  253: "풀",      // 나무돌이 Grovyle
  254: "풀",      // 나무킹 Sceptile
  255: "불꽃",    // 아차모 Torchic
  256: "불꽃",    // 영치코 Combusken
  257: "불꽃",    // 번치코 Blaziken
  258: "물",      // 물짱이 Mudkip
  259: "물",      // 늪짱이 Marshtomp
  260: "물",      // 대짱이 Swampert
  261: "악",      // 포챠나 Poochyena
  262: "악",      // 그라에나 Mightyena
  263: "노말",    // 지그제구리 Zigzagoon
  264: "노말",    // 직구리 Linoone
  265: "벌레",    // 개무소 Wurmple
  266: "벌레",    // 실쿤 Silcoon
  267: "벌레",    // 뷰티플라이 Beautifly
  268: "벌레",    // 카스쿤 Cascoon
  269: "벌레",    // 독케일 Dustox
  270: "물",      // 연꽃몬 Lotad
  271: "물",      // 로토스 Lombre
  272: "물",      // 로파파 Ludicolo
  273: "풀",      // 도토링 Seedot
  274: "풀",      // 잎새코 Nuzleaf
  275: "풀",      // 다탱구 Shiftry
  276: "노말",    // 테일로 Taillow
  277: "노말",    // 스왈로 Swellow
  278: "물",      // 갈모매 Wingull
  279: "물",      // 패리퍼 Pelipper
  280: "에스퍼",  // 랄토스 Ralts
  281: "에스퍼",  // 킬리아 Kirlia
  282: "에스퍼",  // 가디안 Gardevoir
  283: "벌레",    // 비구술 Surskit
  284: "벌레",    // 비나방 Masquerain
  285: "풀",      // 버섯꼬 Shroomish
  286: "풀",      // 버섯모 Breloom
  287: "노말",    // 게을로 Slakoth
  288: "노말",    // 발바로 Vigoroth
  289: "노말",    // 게을킹 Slaking
  290: "벌레",    // 토중몬 Nincada
  291: "벌레",    // 아이앤트 Ninjask
  292: "벌레",    // 껍질몬 Shedinja
  293: "노말",    // 소곤룡 Whismur
  294: "노말",    // 노공룡 Loudred
  295: "노말",    // 폭음룡 Exploud
  296: "격투",    // 마크탕 Makuhita
  297: "격투",    // 하리뭉 Hariyama
  298: "노말",    // 아짱 Azurill
  299: "바위",    // 코코파스 Nosepass
  300: "노말",    // 에나비 Skitty
  301: "노말",    // 델케티 Delcatty
  302: "악",      // 깜까미 Sableye
  303: "강철",    // 입치트 Mawile
  304: "강철",    // 코고나 Aron
  305: "강철",    // 코동 Lairon
  306: "강철",    // 보스로라 Aggron
  307: "격투",    // 요가랑 Meditite
  308: "격투",    // 요가램 Medicham
  309: "전기",    // 썬더라이 Electrike
  310: "전기",    // 썬더볼트 Manectric
  311: "전기",    // 플러시 Plusle
  312: "전기",    // 마이농 Minun
  313: "벌레",    // 볼비트 Volbeat
  314: "벌레",    // 네오비트 Illumise
  315: "풀",      // 로젤리아 Roselia
  316: "독",      // 꼴깍몬 Gulpin
  317: "독",      // 꿀꺽몬 Swalot
  318: "물",      // 샤프니아 Carvanha
  319: "물",      // 샤크니아 Sharpedo
  320: "물",      // 고래왕자 Wailmer
  321: "물",      // 고래왕 Wailord
  322: "불꽃",    // 둔타 Numel
  323: "불꽃",    // 폭타 Camerupt
  324: "불꽃",    // 코터스 Torkoal
  325: "에스퍼",  // 피그점프 Spoink
  326: "에스퍼",  // 피그킹 Grumpig
  327: "노말",    // 얼루기 Spinda
  328: "땅",      // 톱치 Trapinch
  329: "땅",      // 비브라바 Vibrava
  330: "땅",      // 플라이곤 Flygon
  331: "풀",      // 선인왕 Cacnea
  332: "풀",      // 밤선인 Cacturne
  333: "노말",    // 파비코 Swablu
  334: "드래곤",  // 파비코리 Altaria
  335: "노말",    // 쟝고 Zangoose
  336: "독",      // 세비퍼 Seviper
  337: "바위",    // 루나톤 Lunatone
  338: "바위",    // 솔록 Solrock
  339: "물",      // 미꾸리 Barboach
  340: "물",      // 메깅 Whiscash
  341: "물",      // 가재군 Corphish
  342: "물",      // 가재장군 Crawdaunt
  343: "땅",      // 오뚝군 Baltoy
  344: "땅",      // 점토도리 Claydol
  345: "바위",    // 릴링 Lileep
  346: "바위",    // 릴리요 Cradily
  347: "바위",    // 아노딥스 Anorith
  348: "바위",    // 아말도 Armaldo
  349: "물",      // 빈티나 Feebas
  350: "물",      // 밀로틱 Milotic
  351: "노말",    // 캐스퐁 Castform
  352: "노말",    // 켈리몬 Kecleon
  353: "고스트",  // 어둠대신 Shuppet
  354: "고스트",  // 다크펫 Banette
  355: "고스트",  // 해골몽 Duskull
  356: "고스트",  // 미라몽 Dusclops
  357: "풀",      // 트로피우스 Tropius
  358: "에스퍼",  // 치렁 Chimecho
  359: "악",      // 앱솔 Absol
  360: "에스퍼",  // 마자붕 Wynaut
  361: "얼음",    // 눈꼬마 Snorunt
  362: "얼음",    // 얼음귀신 Glalie
  363: "얼음",    // 대굴레오 Spheal
  364: "얼음",    // 씨레오 Sealeo
  365: "얼음",    // 씨카이저 Walrein
  366: "물",      // 진주몽 Clamperl
  367: "물",      // 헌터 Huntail
  368: "물",      // 분홍장이 Gorebyss
  369: "물",      // 시라칸 Relicanth
  370: "물",      // 사랑동이 Luvdisc
  371: "드래곤",  // 아공이 Bagon
  372: "드래곤",  // 쉘곤 Shelgon
  373: "드래곤",  // 보만다 Salamence
  374: "강철",    // 메탕 Beldum
  375: "강철",    // 메탕구 Metang
  376: "강철",    // 메타그로스 Metagross
  377: "바위",    // 레지락 Regirock
  378: "얼음",    // 레지아이스 Regice
  379: "강철",    // 레지스틸 Registeel
  380: "드래곤",  // 라티아스 Latias
  381: "드래곤",  // 라티오스 Latios
  382: "물",      // 가이오가 Kyogre
  383: "땅",      // 그란돈 Groudon
  384: "드래곤",  // 레쿠쟈 Rayquaza
  385: "강철",    // 지라치 Jirachi
  386: "에스퍼",  // 테오키스 Deoxys

  // ── Gen 4 (387–493) ──────────────────────────────────────────────
  387: "풀",      // 모부기 Turtwig
  388: "풀",      // 수풀부기 Grotle
  389: "풀",      // 토대부기 Torterra
  390: "불꽃",    // 불꽃숭이 Chimchar
  391: "불꽃",    // 파이숭이 Monferno
  392: "불꽃",    // 초염몽 Infernape
  393: "물",      // 팽도리 Piplup
  394: "물",      // 팽태자 Prinplup
  395: "물",      // 엠페르트 Empoleon
  396: "노말",    // 찌르꼬 Starly
  397: "노말",    // 찌르버드 Staravia
  398: "노말",    // 찌르호크 Staraptor
  399: "노말",    // 비버니 Bidoof
  400: "노말",    // 비버통 Bibarel
  401: "벌레",    // 귀뚤뚜기 Kricketot
  402: "벌레",    // 귀뚤톡크 Kricketune
  403: "전기",    // 꼬링크 Shinx
  404: "전기",    // 럭시오 Luxio
  405: "전기",    // 렌트라 Luxray
  406: "풀",      // 꼬몽울 Budew
  407: "풀",      // 로즈레이드 Roserade
  408: "바위",    // 두개도스 Cranidos
  409: "바위",    // 램펄드 Rampardos
  410: "바위",    // 방패키드 Shieldon
  411: "바위",    // 바리톱스 Bastiodon
  412: "벌레",    // 도롱충이 Burmy
  413: "벌레",    // 도롱마담 Wormadam
  414: "벌레",    // 나메일 Mothim
  415: "벌레",    // 세꿀버리 Combee
  416: "벌레",    // 비퀸 Vespiquen
  417: "전기",    // 파치리스 Pachirisu
  418: "물",      // 부이젤 Buizel
  419: "물",      // 플로젤 Floatzel
  420: "풀",      // 체리버 Cherubi
  421: "풀",      // 체리꼬 Cherrim
  422: "물",      // 깝질무 Shellos
  423: "물",      // 트리토돈 Gastrodon
  424: "노말",    // 겟핸보숭 Ambipom
  425: "고스트",  // 흔들풍손 Drifloon
  426: "고스트",  // 둥실라이드 Drifblim
  427: "노말",    // 이어롤 Buneary
  428: "노말",    // 이어롭 Lopunny
  429: "고스트",  // 무우마직 Mismagius
  430: "악",      // 돈크로우 Honchkrow
  431: "노말",    // 나옹마 Glameow
  432: "노말",    // 몬냥이 Purugly
  433: "에스퍼",  // 셀비 Chingling
  434: "독",      // 스컹뿡 Stunky
  435: "독",      // 스컹탱크 Skuntank
  436: "강철",    // 동미러 Bronzor
  437: "강철",    // 동탁군 Bronzong
  438: "바위",    // 꼬지지 Bonsly
  439: "에스퍼",  // 흉내내 Mime Jr.
  440: "노말",    // 핑복 Happiny
  441: "노말",    // 페라페 Chatot
  442: "고스트",  // 화강돌 Spiritomb
  443: "드래곤",  // 딥상어동 Gible
  444: "드래곤",  // 한바이트 Gabite
  445: "드래곤",  // 한카리아스 Garchomp
  446: "노말",    // 먹고자 Munchlax
  447: "격투",    // 리오르 Riolu
  448: "격투",    // 루카리오 Lucario
  449: "땅",      // 히포포타스 Hippopotas
  450: "땅",      // 하마돈 Hippowdon
  451: "독",      // 스콜피 Skorupi
  452: "독",      // 드래피온 Drapion
  453: "독",      // 삐딱구리 Croagunk
  454: "독",      // 독개굴 Toxicroak
  455: "풀",      // 무스틈니 Carnivine
  456: "물",      // 형광어 Finneon
  457: "물",      // 네오라이트 Lumineon
  458: "물",      // 타만타 Mantyke
  459: "풀",      // 눈꽃동이 Snover
  460: "풀",      // 눈설왕 Abomasnow
  461: "악",      // 포푸니라 Weavile
  462: "전기",    // 자포코일 Magnezone
  463: "노말",    // 내룸벨버 Lickilicky
  464: "땅",      // 거대코뿌리 Rhyperior
  465: "풀",      // 덩쿠림보 Tangrowth
  466: "전기",    // 에레키블 Electivire
  467: "불꽃",    // 마그마번 Magmortar
  468: "페어리",  // 토게키스 Togekiss
  469: "벌레",    // 메가야느마 Yanmega
  470: "풀",      // 리피아 Leafeon
  471: "얼음",    // 글레이시아 Glaceon
  472: "땅",      // 글라이온 Gliscor
  473: "얼음",    // 맘모꾸리 Mamoswine
  474: "노말",    // 폴리곤Z Porygon-Z
  475: "에스퍼",  // 엘레이드 Gallade
  476: "바위",    // 대코파스 Probopass
  477: "고스트",  // 야느프리 Dusknoir
  478: "얼음",    // 눈여아 Froslass
  479: "전기",    // 로토무 Rotom
  480: "에스퍼",  // 유크시 Uxie
  481: "에스퍼",  // 엠라이트 Mesprit
  482: "에스퍼",  // 아그놈 Azelf
  483: "강철",    // 디아루가 Dialga
  484: "물",      // 펄기아 Palkia
  485: "불꽃",    // 히드런 Heatran
  486: "노말",    // 레지기가스 Regigigas
  487: "고스트",  // 기라티나 Giratina
  488: "에스퍼",  // 크레세리아 Cresselia
  489: "물",      // 피오네 Phione
  490: "물",      // 마나피 Manaphy
  491: "악",      // 다크라이 Darkrai
  492: "풀",      // 쉐이미 Shaymin
  493: "노말",    // 아르세우스 Arceus

  // ── Gen 5 (494–649) ──────────────────────────────────────────────
  494: "에스퍼",  // 비크티니 Victini
  495: "풀",      // 뱀독풀 Snivy
  496: "풀",      // 데꾸리 Servine
  497: "풀",      // 샤로다 Serperior
  498: "불꽃",    // 뚜꾸리 Tepig
  499: "불꽃",    // 챠오꿀 Pignite
  500: "불꽃",    // 염무왕 Emboar
  501: "물",      // 수댕이 Oshawott
  502: "물",      // 쌍검자비 Dewott
  503: "물",      // 대검귀 Samurott
  504: "노말",    // 보르쥐 Patrat
  505: "노말",    // 보르그 Watchog
  506: "노말",    // 요테리 Lillipup
  507: "노말",    // 하데리어 Herdier
  508: "노말",    // 바랜드 Stoutland
  509: "악",      // 친치라 Purrloin
  510: "악",      // 레파르다스 Liepard
  511: "풀",      // 야나프 Pansage
  512: "풀",      // 야나키 Simisage
  513: "불꽃",    // 바오프 Pansear
  514: "불꽃",    // 바오키 Simisear
  515: "물",      // 앗차프 Panpour
  516: "물",      // 앗차키 Simipour
  517: "에스퍼",  // 몽나 Munna
  518: "에스퍼",  // 몽얌나 Musharna
  519: "노말",    // 콩둘기 Pidove
  520: "노말",    // 유토브 Tranquill
  521: "노말",    // 켄호로우 Unfezant
  522: "전기",    // 줄전기 Blitzle
  523: "전기",    // 제브라이카 Zebstrika
  524: "바위",    // 단굴 Roggenrola
  525: "바위",    // 암트르 Boldore
  526: "바위",    // 기가이어스 Gigalith
  527: "에스퍼",  // 또르박쥐 Woobat
  528: "에스퍼",  // 맘박쥐 Swoobat
  529: "땅",      // 두더류 Drilbur
  530: "땅",      // 몰드류 Excadrill
  531: "노말",    // 다부니 Audino
  532: "격투",    // 한일랜드 Timburr
  533: "격투",    // 모집랜드 Gurdurr
  534: "격투",    // 노보청 Conkeldurr
  535: "물",      // 동챙이 Tympole
  536: "물",      // 두챙이 Palpitoad
  537: "물",      // 로또스왓 Seismitoad
  538: "격투",    // 던지미 Throh
  539: "격투",    // 타격귀 Sawk
  540: "벌레",    // 두르보 Sewaddle
  541: "벌레",    // 두르쿤 Swadloon
  542: "벌레",    // 모아머 Leavanny
  543: "벌레",    // 마디네 Venipede
  544: "벌레",    // 휠구 Whirlipede
  545: "벌레",    // 펜드라 Scolipede
  546: "풀",      // 모코코 Cottonee
  547: "풀",      // 엘풍 Whimsicott
  548: "풀",      // 치코리 Petilil
  549: "풀",      // 드레디어 Lilligant
  550: "물",      // 배쓰나이 Basculin
  551: "땅",      // 메구로코 Sandile
  552: "땅",      // 와루비루 Krokorok
  553: "땅",      // 악비르 Krookodile
  554: "불꽃",    // 달막화 Darumaka
  555: "불꽃",    // 불비달마 Darmanitan
  556: "풀",      // 마라카치 Maractus
  557: "벌레",    // 돌살이 Dwebble
  558: "벌레",    // 암팰리스 Crustle
  559: "악",      // 곤율랭 Scraggy
  560: "악",      // 곤율거니 Scrafty
  561: "에스퍼",  // 심보러 Sigilyph
  562: "고스트",  // 데스마스 Yamask
  563: "고스트",  // 데스니칸 Cofagrigus
  564: "물",      // 프로토가 Tirtouga
  565: "물",      // 늑골라 Carracosta
  566: "바위",    // 아켄 Archen
  567: "바위",    // 아케오스 Archeops
  568: "독",      // 깨봉이 Trubbish
  569: "독",      // 더스트나 Garbodor
  570: "악",      // 조로아 Zorua
  571: "악",      // 조로아크 Zoroark
  572: "노말",    // 츄리네 Minccino
  573: "노말",    // 치라치노 Cinccino
  574: "에스퍼",  // 음번 Gothita
  575: "에스퍼",  // 음번이 Gothorita
  576: "에스퍼",  // 음벼나 Gothitelle
  577: "에스퍼",  // 단셋 Solosis
  578: "에스퍼",  // 두셋 Duosion
  579: "에스퍼",  // 란쿨루스 Reuniclus
  580: "물",      // 꼬지보리 Ducklett
  581: "물",      // 스완나 Swanna
  582: "얼음",    // 바닐프티 Vanillite
  583: "얼음",    // 바닐리치 Vanillish
  584: "얼음",    // 배바닐라 Vanilluxe
  585: "노말",    // 사철록 Deerling
  586: "노말",    // 바라철록 Sawsbuck
  587: "전기",    // 에몽가 Emolga
  588: "벌레",    // 딱정곤 Karrablast
  589: "벌레",    // 슈바르고 Escavalier
  590: "풀",      // 깜놀버슛 Foongus
  591: "풀",      // 뽀록나 Amoonguss
  592: "물",      // 탱그릴 Frillish
  593: "물",      // 부르룽겔 Jellicent
  594: "물",      // 맘복치 Alomomola
  595: "벌레",    // 파라꿀 Joltik
  596: "벌레",    // 전툴라 Galvantula
  597: "풀",      // 철시드 Ferroseed
  598: "풀",      // 너트령 Ferrothorn
  599: "강철",    // 기어르 Klink
  600: "강철",    // 기기어르 Klang
  601: "강철",    // 기기기어르 Klinklang
  602: "전기",    // 저리어 Tynamo
  603: "전기",    // 저리릴 Eelektrik
  604: "전기",    // 저리더프 Eelektross
  605: "에스퍼",  // 비조푸 Elgyem
  606: "에스퍼",  // 비조도 Beheeyem
  607: "고스트",  // 불켜미 Litwick
  608: "고스트",  // 램프라 Lampent
  609: "고스트",  // 샹델라 Chandelure
  610: "드래곤",  // 터검니 Axew
  611: "드래곤",  // 액슨도 Fraxure
  612: "드래곤",  // 액스라이즈 Haxorus
  613: "얼음",    // 코고미 Cubchoo
  614: "얼음",    // 툰베어 Beartic
  615: "얼음",    // 프리지오 Cryogonal
  616: "벌레",    // 달팽이로 Shelmet
  617: "벌레",    // 어지리더 Accelgor
  618: "땅",      // 메더 Stunfisk
  619: "격투",    // 비조도리 Mienfoo
  620: "격투",    // 비조도리오 Mienshao
  621: "드래곤",  // 크리만 Druddigon
  622: "땅",      // 골루그 Golett
  623: "땅",      // 골루그 Golurk
  624: "악",      // 자망칼 Pawniard
  625: "악",      // 절각참 Bisharp
  626: "노말",    // 버프론 Bouffalant
  627: "노말",    // 단단지 Rufflet
  628: "노말",    // 워글 Braviary
  629: "악",      // 벌찌 Vullaby
  630: "악",      // 버랜지나 Mandibuzz
  631: "불꽃",    // 앤티골 Heatmor
  632: "벌레",    // 아이앤트 Durant
  633: "악",      // 모노두 Deino
  634: "악",      // 디헤드 Zweilous
  635: "악",      // 삼삼드래 Hydreigon
  636: "벌레",    // 활화르바 Larvesta
  637: "벌레",    // 불카모스 Volcarona
  638: "강철",    // 코바르온 Cobalion
  639: "바위",    // 테라키온 Terrakion
  640: "풀",      // 비리디온 Virizion
  641: "비행",    // 토네로스 Tornadus
  642: "전기",    // 볼트로스 Thundurus
  643: "드래곤",  // 레시라무 Reshiram
  644: "드래곤",  // 제크로무 Zekrom
  645: "땅",      // 랜드로스 Landorus
  646: "드래곤",  // 큐레무 Kyurem
  647: "물",      // 케르디오 Keldeo
  648: "노말",    // 메로엣타 Meloetta
  649: "벌레",    // 게노세크트 Genesect

  // ── Gen 6 (650–721) ──────────────────────────────────────────────
  650: "풀",      // 도치마론 Chespin
  651: "풀",      // 도치보구 Quilladin
  652: "풀",      // 브리가론 Chesnaught
  653: "불꽃",    // 푸호꼬 Fennekin
  654: "불꽃",    // 테르나 Braixen
  655: "불꽃",    // 마폭시 Delphox
  656: "물",      // 개구마르 Froakie
  657: "물",      // 개굴반장 Frogadier
  658: "물",      // 개굴닌자 Greninja
  659: "노말",    // 파르빗 Bunnelby
  660: "노말",    // 파르토 Diggersby
  661: "노말",    // 화살꼬빈 Fletchling
  662: "불꽃",    // 불화살빈 Fletchinder
  663: "불꽃",    // 파이어로 Talonflame
  664: "벌레",    // 분이벌레 Scatterbug
  665: "벌레",    // 분떠도리 Spewpa
  666: "벌레",    // 비비용 Vivillon
  667: "불꽃",    // 레옹 Litleo
  668: "불꽃",    // 화염레오 Pyroar
  669: "페어리",  // 플라베베 Flabébé
  670: "페어리",  // 플라엣테 Floette
  671: "페어리",  // 플라제스 Florges
  672: "풀",      // 메이클레오 Skiddo
  673: "풀",      // 고고트 Gogoat
  674: "격투",    // 판짱 Pancham
  675: "격투",    // 판짱구 Pangoro
  676: "노말",    // 트리미앙 Furfrou
  677: "에스퍼",  // 냐스퍼 Espurr
  678: "에스퍼",  // 냐오닉스 Meowstic
  679: "강철",    // 단칼빙 Honedge
  680: "강철",    // 쌍칼아빙 Doublade
  681: "강철",    // 킬가르도 Aegislash
  682: "페어리",  // 슈쁘 Spritzee
  683: "페어리",  // 시트론 Aromatisse
  684: "페어리",  // 사탕솜 Swirlix
  685: "페어리",  // 슈크림니 Slurpuff
  686: "악",      // 마꾸리 Inkay
  687: "악",      // 칼라마네로 Malamar
  688: "바위",    // 거북손데스 Binacle
  689: "바위",    // 거북손손 Barbaracle
  690: "독",      // 모래꼬여 Skrelp
  691: "독",      // 드래캄 Dragalge
  692: "물",      // 가재격노 Clauncher
  693: "물",      // 블로스터 Clawitzer
  694: "전기",    // 일레도리자드 Helioptile
  695: "전기",    // 에레키게라 Heliolisk
  696: "바위",    // 티고라스 Tyrunt
  697: "바위",    // 견고라스 Tyrantrum
  698: "바위",    // 아마루스 Amaura
  699: "바위",    // 아마루르가 Aurorus
  700: "페어리",  // 님피아 Sylveon
  701: "격투",    // 루차불 Hawlucha
  702: "전기",    // 데덴네 Dedenne
  703: "바위",    // 멜리시 Carbink
  704: "드래곤",  // 미끄메라 Goomy
  705: "드래곤",  // 미끄네일 Sliggoo
  706: "드래곤",  // 미끄래곤 Goodra
  707: "강철",    // 자물집게 Klefki
  708: "고스트",  // 출통이 Phantump
  709: "고스트",  // 다부엉 Trevenant
  710: "고스트",  // 호바귀 Pumpkaboo
  711: "고스트",  // 펌프킨 Gourgeist
  712: "얼음",    // 꽁어름 Bergmite
  713: "얼음",    // 크레베이스 Avalugg
  714: "비행",    // 음파못치 Noibat
  715: "비행",    // 음파괴왕 Noivern
  716: "페어리",  // 제르네아스 Xerneas
  717: "악",      // 이벨타르 Yveltal
  718: "드래곤",  // 지가르데 Zygarde
  719: "바위",    // 디안시 Diancie
  720: "에스퍼",  // 후파 Hoopa
  721: "불꽃",    // 볼케니온 Volcanion

  // ── Gen 7 (722–809) ──────────────────────────────────────────────
  722: "풀",      // 나몰빼미 Rowlet
  723: "풀",      // 빼미스로우 Dartrix
  724: "풀",      // 모크나이퍼 Decidueye
  725: "불꽃",    // 냐오불 Litten
  726: "불꽃",    // 어흥염 Torracat
  727: "불꽃",    // 내무한별 Incineroar
  728: "물",      // 누리공 Popplio
  729: "물",      // 해핑이 Brionne
  730: "물",      // 누리레느 Primarina
  731: "노말",    // 콕코구리 Pikipek
  732: "노말",    // 답구리 Trumbeak
  733: "노말",    // 왕큰부리 Toucannon
  734: "노말",    // 형사구리 Yungoos
  735: "노말",    // 형사구리스 Gumshoos
  736: "벌레",    // 0설탕벌레 Grubbin
  737: "벌레",    // 충전지 Charjabug
  738: "벌레",    // 투구뿌논 Vikavolt
  739: "격투",    // 오기지게 Crabrawler
  740: "격투",    // 케오피에라 Crabominable
  741: "불꽃",    // 춤추새 Oricorio (base form: Baile)
  742: "벌레",    // 부푸린 Cutiefly
  743: "벌레",    // 리본 Ribombee
  744: "바위",    // 암멍이 Rockruff
  745: "바위",    // 루가루암 Lycanroc
  746: "물",      // 약어리 Wishiwashi
  747: "독",      // 토게데마루 Mareanie
  748: "독",      // 더시마사리 Toxapex
  749: "땅",      // 머드나기 Mudbray
  750: "땅",      // 만마드 Mudsdale
  751: "물",      // 깨알물거미 Dewpider
  752: "물",      // 깨알 큰 거미 Araquanid
  753: "풀",      // 짜랑랑이 Fomantis
  754: "풀",      // 라란티스 Lurantis
  755: "풀",      // 모르페코 Morelull
  756: "풀",      // 마셰이드 Shiinotic
  757: "독",      // 깜눈크 Salandit
  758: "독",      // 살라마 Salazzle
  759: "노말",    // 포곰곰 Stufful
  760: "노말",    // 이븐곰 Bewear
  761: "풀",      // 달콤참 Bounsweet
  762: "풀",      // 달뜨속 Steenee
  763: "풀",      // 달코퀸 Tsareena
  764: "페어리",  // 큐아링 Comfey
  765: "노말",    // 하랑우탄 Oranguru
  766: "격투",    // 자랑갱이 Passimian
  767: "벌레",    // 꿀벌이 Wimpod
  768: "벌레",    // 갑주무사 Golisopod
  769: "고스트",  // 모래꿈치 Sandygast
  770: "고스트",  // 모래성이당 Palossand
  771: "물",      // 해무기 Pyukumuku
  772: "노말",    // 타입:널 Type: Null
  773: "노말",    // 실버디 Silvally
  774: "바위",    // 미뇽 Minior
  775: "노말",    // 자말로크 Komala
  776: "불꽃",    // 폭거북손 Turtonator
  777: "전기",    // 토게데마루 Togedemaru
  778: "고스트",  // 따라큐 Mimikyu
  779: "물",      // 입술이 Bruxish
  780: "노말",    // 짜랑꼬 Drampa
  781: "고스트",  // 타타륜 Dhelmise
  782: "드래곤",  // 미끄나매 Jangmo-o
  783: "드래곤",  // 미끄렁 Hakamo-o
  784: "드래곤",  // 짜랑이고라 Kommo-o
  785: "전기",    // 카푸꼬꼬꼭 Tapu Koko
  786: "에스퍼",  // 카푸나비나 Tapu Lele
  787: "풀",      // 카푸브루루 Tapu Bulu
  788: "물",      // 카푸느지느 Tapu Fini
  789: "에스퍼",  // 코스모그 Cosmog
  790: "에스퍼",  // 코스모움 Cosmoem
  791: "에스퍼",  // 솔가레오 Solgaleo
  792: "에스퍼",  // 루나아라 Lunala
  793: "바위",    // 텅비드 Nihilego
  794: "벌레",    // 매시붕 Buzzwole
  795: "벌레",    // 페로코체 Pheromosa
  796: "전기",    // 전수목 Xurkitree
  797: "강철",    // 철화구야 Celesteela
  798: "풀",      // 종이신도 Kartana (Grass primary)
  799: "악",      // 악비아르 Guzzlord
  800: "에스퍼",  // 네크로즈마 Necrozma
  801: "강철",    // 마기아나 Magearna
  802: "격투",    // 마샤도 Marshadow
  803: "독",      // 베베놈 Poipole
  804: "독",      // 아교무즈 Naganadel
  805: "바위",    // 차곡차곡 Stakataka
  806: "불꽃",    // 두파팟 Blacephalon
  807: "전기",    // 제라오라 Zeraora
  808: "강철",    // 멜탄 Meltan
  809: "강철",    // 멜메탈 Melmetal

  // ── Gen 8 (810–905) ──────────────────────────────────────────────
  810: "풀",      // 흥나숭 Grookey
  811: "풀",      // 채키몽 Thwackey
  812: "풀",      // 고릴타 Rillaboom
  813: "불꽃",    // 염버니 Scorbunny
  814: "불꽃",    // 래비풋 Raboot
  815: "불꽃",    // 에이스번 Cinderace
  816: "물",      // 울머기 Sobble
  817: "물",      // 누겔레옹 Drizzile
  818: "물",      // 인텔리레온 Inteleon
  819: "노말",    // 단지래기 Skwovet
  820: "노말",    // 떡잎새 Greedent
  821: "비행",    // 꼬링크 Rookidee
  822: "비행",    // 꼬자작 Corvisquire
  823: "비행",    // 아머까오 Corviknight
  824: "벌레",    // 두마리 Blipbug
  825: "벌레",    // 두벌레 Dottler
  826: "벌레",    // 이올브 Orbeetle
  827: "악",      // 토키오 Nickit
  828: "악",      // 폭슬라이 Thievul
  829: "풀",      // 소민이 Gossifleur
  830: "풀",      // 백솜모카 Eldegoss
  831: "노말",    // 우르 Wooloo
  832: "노말",    // 배릴리 Dubwool
  833: "물",      // 어리표범 Chewtle
  834: "물",      // 마릴리브로 Drednaw
  835: "전기",    // 멍짖코 Yamper
  836: "전기",    // 부르룬패스 Boltund
  837: "바위",    // 단탄 Rolycoly
  838: "바위",    // 탄동 Carkol
  839: "바위",    // 자이멍구이 Coalossal
  840: "풀",      // 사과주 Applin
  841: "풀",      // 애프룬 Flapple
  842: "풀",      // 단지래기 Appletun
  843: "땅",      // 모래탈진 Silicobra
  844: "땅",      // 사다이작 Sandaconda
  845: "비행",    // 우비크 Cramorant
  846: "물",      // 가라도르 Arrokuda
  847: "물",      // 어망크 Barraskewda
  848: "전기",    // 일레톤 Toxel
  849: "전기",    // 스트린더 Toxtricity
  850: "벌레",    // 화르륵 Sizzlipede
  851: "벌레",    // 다태우지네 Centiskorch
  852: "격투",    // 작구리 Clobbopus
  853: "격투",    // 케오피에르 Grapploct
  854: "고스트",  // 찻탕복 Sinistea
  855: "고스트",  // 폿빛해리 Polteageist
  856: "에스퍼",  // 헤롱은빛쥐 Hatenna
  857: "에스퍼",  // 헤롱미인 Hattrem
  858: "에스퍼",  // 헤롱크리 Hatterene
  859: "악",      // 임펩 Impidimp
  860: "악",      // 모르페코 Morgrem
  861: "악",      // 오롱털 Grimmsnarl
  862: "악",      // 오바몽 Obstagoon
  863: "노말",    // 페르시온 Perrserker
  864: "고스트",  // 큐꾸리 Cursola
  865: "격투",    // 파오리 Sirfetch'd
  866: "에스퍼",  // 마임꽁꽁 Mr. Rime
  867: "땅",      // 데스판 Runerigus
  868: "페어리",  // 우유차 Milcery
  869: "페어리",  // 마휘핑 Alcremie
  870: "격투",    // 끼리꼬꼬 Falinks
  871: "전기",    // 따라큐로치 Pincurchin
  872: "얼음",    // 눈쓰개 Snom
  873: "얼음",    // 모스노우 Frosmoth
  874: "바위",    // 머쓱마 Stonjourner
  875: "얼음",    // 빙큐보 Eiscue
  876: "에스퍼",  // 에써르 Indeedee
  877: "전기",    // 모르페코 Morpeko
  878: "강철",    // 끄으적 Cufant
  879: "강철",    // 코퍼라자 Copperajah
  880: "전기",    // 파치라곤 Dracozolt
  881: "전기",    // 파치르돈 Arctozolt
  882: "물",      // 어래곤 Dracovish
  883: "물",      // 어치르돈 Arctovish
  884: "강철",    // 두랄도 Duraludon
  885: "드래곤",  // 드라꼬 Dreepy
  886: "드래곤",  // 도라꼰 Drakloak
  887: "드래곤",  // 드래펄트 Dragapult
  888: "페어리",  // 자시안 Zacian
  889: "격투",    // 자마젠타 Zamazenta
  890: "독",      // 무한다이노 Eternatus
  891: "격투",    // 다태우지 Kubfu
  892: "격투",    // 우라오스 Urshifu
  893: "악",      // 자루도 Zarude
  894: "전기",    // 레지에레키 Regieleki
  895: "드래곤",  // 레지드래고 Regidrago
  896: "얼음",    // 블리자포스 Glastrier
  897: "고스트",  // 레이스포스 Spectrier
  898: "에스퍼",  // 버드렉스 Calyrex
  899: "노말",    // 따라큐 Wyrdeer
  900: "벌레",    // 비비온 Kleavor
  901: "땅",      // 베어물 Ursaluna
  902: "물",      // 대쓰여너 Basculegion
  903: "격투",    // 포푸니라 Sneasler
  904: "독",      // 대신침바루 Overqwil
  905: "페어리",  // 러브로스 Enamorus

  // ── Gen 9 (906–1025) ─────────────────────────────────────────────
  906: "풀",      // 나린냥 Sprigatito
  907: "풀",      // 나리림냥 Floragato
  908: "풀",      // 마스카나 Meowscarada
  909: "불꽃",    // 뜨아거 Fuecoco
  910: "불꽃",    // 뜨악고 Crocalor
  911: "불꽃",    // 라우드본 Skeledirge
  912: "물",      // 꼬록 Quaxly
  913: "물",      // 꽉꽉도리 Quaxwell
  914: "물",      // 웨이니발 Quaquaval
  915: "노말",    // 미니브 Lechonk
  916: "노말",    // 위감자 Oinkologne
  917: "벌레",    // 두벌레 Tarountula
  918: "벌레",    // 두지벌레 Spidops
  919: "벌레",    // 비춤벌레 Nymble
  920: "벌레",    // 차르빈 Lokix
  921: "노말",    // 빠르모 Pawmi
  922: "전기",    // 빠르모트 Pawmo
  923: "전기",    // 빠르몽 Pawmot
  924: "노말",    // 두마리꼬마 Tandemaus
  925: "노말",    // 마우스홀드 Maushold
  926: "노말",    // 복어퐁 Fidough
  927: "페어리",  // 빵빵바 Dachsbun
  928: "풀",      // 모루숨 Smoliv
  929: "풀",      // 올리니 Dolliv
  930: "풀",      // 올리르바 Arboliva
  931: "노말",    // 짹우지 Squawkabilly
  932: "바위",    // 도롱이 Nacli
  933: "바위",    // 도롱이로 Naclstack
  934: "바위",    // 키키링 Garganacl
  935: "불꽃",    // 차르코 Charcadet
  936: "불꽃",    // 갑인다 Armarouge
  937: "불꽃",    // 묘두덕 Ceruledge
  938: "전기",    // 우락스 Tadbulb
  939: "전기",    // 전수룡 Bellibolt
  940: "전기",    // 캥카리 Wattrel
  941: "전기",    // 옹망치 Kilowattrel
  942: "악",      // 망망이 Maschiff
  943: "악",      // 마피티프 Mabosstiff
  944: "독",      // 스푸기 Shroodle
  945: "독",      // 우락스 Grafaiai
  946: "풀",      // 콘재나 Bramblin
  947: "풀",      // 콘투인 Brambleghast
  948: "땅",      // 토오로 Toedscool
  949: "땅",      // 토오로기 Toedscruel
  950: "바위",    // 클립즈 Klawf
  951: "풀",      // 첩푸 Capsakid
  952: "풀",      // 스코빌리언 Scovillain
  953: "벌레",    // 짜랜드 Rellor
  954: "벌레",    // 럭쿠리 Rabsca
  955: "에스퍼",  // 플라이톨 Flittle
  956: "에스퍼",  // 에스파시안 Espathra
  957: "노말",    // 어리짱이 Tinkatink
  958: "페어리",  // 어리쿠하 Tinkatuff
  959: "페어리",  // 통통허크 Tinkaton
  960: "물",      // 진색나이 Wiglett
  961: "물",      // 트리톳보스 Wugtrio
  962: "비행",    // 시비꼬 Bombirdier
  963: "물",      // 마끼나 Finizen
  964: "물",      // 돌핀맨 Palafin
  965: "강철",    // 거북이서 Varoom
  966: "강철",    // 머신부 Revavroom
  967: "드래곤",  // 모토토카게 Cyclizar
  968: "강철",    // 사다이짱 Orthworm
  969: "바위",    // 보과지 Glimmet
  970: "바위",    // 보과지작 Glimmora
  971: "고스트",  // 부르룽 Greavard
  972: "고스트",  // 그레이브가드 Houndstone
  973: "비행",    // 플라밍고 Flamigo
  974: "얼음",    // 모스노우 Cetoddle
  975: "얼음",    // 케이르 Cetitan
  976: "물",      // 베라카스 Veluza
  977: "물",      // 두디로 Dondozo
  978: "드래곤",  // 토하지오스 Tatsugiri
  979: "격투",    // 어흥염팡 Annihilape
  980: "독",      // 토오로치 Clodsire
  981: "노말",    // 키키링 Farigiraf
  982: "노말",    // 노고고치 Dudunsparce
  983: "악",      // 도도지잔 Kingambit
  984: "땅",      // 그레이트 종 Great Tusk
  985: "페어리",  // 무서운 비명 Scream Tail
  986: "풀",      // 매서운 발톱 Brute Bonnet
  987: "고스트",  // 무서운 갈기 Flutter Mane
  988: "벌레",    // 미친자세 Slither Wing
  989: "전기",    // 모래 자국 Sandy Shocks
  990: "땅",      // 무쇠 발자국 Iron Treads
  991: "얼음",    // 무쇠 통발 Iron Bundle
  992: "격투",    // 무쇠 주먹 Iron Hands
  993: "악",      // 무쇠 목 Iron Jugulis
  994: "불꽃",    // 무쇠 독나방 Iron Moth
  995: "바위",    // 무쇠 가시 Iron Thorns
  996: "드래곤",  // 미끄렁이 Frigibax
  997: "드래곤",  // 빙어룡 Arctibax
  998: "드래곤",  // 세빙룡 Baxcalibur
  999: "고스트",  // 동상이 Gimmighoul
  1000: "강철",   // 사파리주 Gholdengo
  1001: "악",     // 총지엔 Wo-Chien
  1002: "악",     // 파오젠 Chien-Pao
  1003: "악",     // 띵루 Ting-Lu
  1004: "악",     // 위유이 Chi-Yu
  1005: "드래곤", // 포효의 달 Roaring Moon
  1006: "페어리", // 무쇠 무인 Iron Valiant
  1007: "격투",   // 코라이돈 Koraidon
  1008: "전기",   // 미라이돈 Miraidon
  1009: "물",     // 우렁찬 꼬리 Walking Wake
  1010: "풀",     // 무쇠 잎 Iron Leaves
  1011: "풀",     // 사과핵 Dipplin
  1012: "풀",     // 차곡차곡 Poltchageist
  1013: "풀",     // 다과차차 Sinistcha
  1014: "독",     // 모로배운 Okidogi
  1015: "독",     // 키노가싸 Munkidori
  1016: "독",     // 이루카만 Fezandipiti
  1017: "풀",     // 오거폰 Ogerpon
  1018: "강철",   // 브리두라스 Archaludon
  1019: "풀",     // 카라미냥꼬 Hydrapple
  1020: "불꽃",   // 무쇠 양손 Gouging Fire
  1021: "전기",   // 무쇠 머리 Raging Bolt
  1022: "바위",   // 무쇠 가시 Iron Boulder
  1023: "강철",   // 무쇠 신부 Iron Crown
  1024: "노말",   // 테라파고스 Terapagos
  1025: "독",     // 복숭악동 Pecharunt
};
